-- Seed all US counties into jurisdictions table
-- Run this in Supabase SQL Editor

-- First, clear existing test data (optional - comment out if you want to keep existing)
-- DELETE FROM jurisdictions;

-- Insert all US counties
INSERT INTO jurisdictions (jurisdiction_code, state_code, county_name, display_name, status, monthly_license_fee) VALUES
-- Alabama (67 counties)
('al-autauga', 'AL', 'Autauga', 'Autauga County, AL', 'coming_soon', 0),
('al-baldwin', 'AL', 'Baldwin', 'Baldwin County, AL', 'coming_soon', 0),
('al-barbour', 'AL', 'Barbour', 'Barbour County, AL', 'coming_soon', 0),
('al-bibb', 'AL', 'Bibb', 'Bibb County, AL', 'coming_soon', 0),
('al-blount', 'AL', 'Blount', 'Blount County, AL', 'coming_soon', 0),
('al-bullock', 'AL', 'Bullock', 'Bullock County, AL', 'coming_soon', 0),
('al-butler', 'AL', 'Butler', 'Butler County, AL', 'coming_soon', 0),
('al-calhoun', 'AL', 'Calhoun', 'Calhoun County, AL', 'coming_soon', 0),
('al-chambers', 'AL', 'Chambers', 'Chambers County, AL', 'coming_soon', 0),
('al-cherokee', 'AL', 'Cherokee', 'Cherokee County, AL', 'coming_soon', 0),
('al-chilton', 'AL', 'Chilton', 'Chilton County, AL', 'coming_soon', 0),
('al-choctaw', 'AL', 'Choctaw', 'Choctaw County, AL', 'coming_soon', 0),
('al-clarke', 'AL', 'Clarke', 'Clarke County, AL', 'coming_soon', 0),
('al-clay', 'AL', 'Clay', 'Clay County, AL', 'coming_soon', 0),
('al-cleburne', 'AL', 'Cleburne', 'Cleburne County, AL', 'coming_soon', 0),
('al-coffee', 'AL', 'Coffee', 'Coffee County, AL', 'coming_soon', 0),
('al-colbert', 'AL', 'Colbert', 'Colbert County, AL', 'coming_soon', 0),
('al-conecuh', 'AL', 'Conecuh', 'Conecuh County, AL', 'coming_soon', 0),
('al-coosa', 'AL', 'Coosa', 'Coosa County, AL', 'coming_soon', 0),
('al-covington', 'AL', 'Covington', 'Covington County, AL', 'coming_soon', 0),
('al-crenshaw', 'AL', 'Crenshaw', 'Crenshaw County, AL', 'coming_soon', 0),
('al-cullman', 'AL', 'Cullman', 'Cullman County, AL', 'coming_soon', 0),
('al-dale', 'AL', 'Dale', 'Dale County, AL', 'coming_soon', 0),
('al-dallas', 'AL', 'Dallas', 'Dallas County, AL', 'coming_soon', 0),
('al-dekalb', 'AL', 'DeKalb', 'DeKalb County, AL', 'coming_soon', 0),
('al-elmore', 'AL', 'Elmore', 'Elmore County, AL', 'coming_soon', 0),
('al-escambia', 'AL', 'Escambia', 'Escambia County, AL', 'coming_soon', 0),
('al-etowah', 'AL', 'Etowah', 'Etowah County, AL', 'coming_soon', 0),
('al-fayette', 'AL', 'Fayette', 'Fayette County, AL', 'coming_soon', 0),
('al-franklin', 'AL', 'Franklin', 'Franklin County, AL', 'coming_soon', 0),
('al-geneva', 'AL', 'Geneva', 'Geneva County, AL', 'coming_soon', 0),
('al-greene', 'AL', 'Greene', 'Greene County, AL', 'coming_soon', 0),
('al-hale', 'AL', 'Hale', 'Hale County, AL', 'coming_soon', 0),
('al-henry', 'AL', 'Henry', 'Henry County, AL', 'coming_soon', 0),
('al-houston', 'AL', 'Houston', 'Houston County, AL', 'coming_soon', 0),
('al-jackson', 'AL', 'Jackson', 'Jackson County, AL', 'coming_soon', 0),
('al-jefferson', 'AL', 'Jefferson', 'Jefferson County, AL', 'coming_soon', 0),
('al-lamar', 'AL', 'Lamar', 'Lamar County, AL', 'coming_soon', 0),
('al-lauderdale', 'AL', 'Lauderdale', 'Lauderdale County, AL', 'coming_soon', 0),
('al-lawrence', 'AL', 'Lawrence', 'Lawrence County, AL', 'coming_soon', 0),
('al-lee', 'AL', 'Lee', 'Lee County, AL', 'coming_soon', 0),
('al-limestone', 'AL', 'Limestone', 'Limestone County, AL', 'coming_soon', 0),
('al-lowndes', 'AL', 'Lowndes', 'Lowndes County, AL', 'coming_soon', 0),
('al-macon', 'AL', 'Macon', 'Macon County, AL', 'coming_soon', 0),
('al-madison', 'AL', 'Madison', 'Madison County, AL', 'coming_soon', 0),
('al-marengo', 'AL', 'Marengo', 'Marengo County, AL', 'coming_soon', 0),
('al-marion', 'AL', 'Marion', 'Marion County, AL', 'coming_soon', 0),
('al-marshall', 'AL', 'Marshall', 'Marshall County, AL', 'coming_soon', 0),
('al-mobile', 'AL', 'Mobile', 'Mobile County, AL', 'coming_soon', 0),
('al-monroe', 'AL', 'Monroe', 'Monroe County, AL', 'coming_soon', 0),
('al-montgomery', 'AL', 'Montgomery', 'Montgomery County, AL', 'coming_soon', 0),
('al-morgan', 'AL', 'Morgan', 'Morgan County, AL', 'coming_soon', 0),
('al-perry', 'AL', 'Perry', 'Perry County, AL', 'coming_soon', 0),
('al-pickens', 'AL', 'Pickens', 'Pickens County, AL', 'coming_soon', 0),
('al-pike', 'AL', 'Pike', 'Pike County, AL', 'coming_soon', 0),
('al-randolph', 'AL', 'Randolph', 'Randolph County, AL', 'coming_soon', 0),
('al-russell', 'AL', 'Russell', 'Russell County, AL', 'coming_soon', 0),
('al-shelby', 'AL', 'Shelby', 'Shelby County, AL', 'coming_soon', 0),
('al-st-clair', 'AL', 'St. Clair', 'St. Clair County, AL', 'coming_soon', 0),
('al-sumter', 'AL', 'Sumter', 'Sumter County, AL', 'coming_soon', 0),
('al-talladega', 'AL', 'Talladega', 'Talladega County, AL', 'coming_soon', 0),
('al-tallapoosa', 'AL', 'Tallapoosa', 'Tallapoosa County, AL', 'coming_soon', 0),
('al-tuscaloosa', 'AL', 'Tuscaloosa', 'Tuscaloosa County, AL', 'coming_soon', 0),
('al-walker', 'AL', 'Walker', 'Walker County, AL', 'coming_soon', 0),
('al-washington', 'AL', 'Washington', 'Washington County, AL', 'coming_soon', 0),
('al-wilcox', 'AL', 'Wilcox', 'Wilcox County, AL', 'coming_soon', 0),
('al-winston', 'AL', 'Winston', 'Winston County, AL', 'coming_soon', 0),

-- Alaska (30 boroughs/census areas)
('ak-aleutians-east', 'AK', 'Aleutians East', 'Aleutians East Borough, AK', 'coming_soon', 0),
('ak-aleutians-west', 'AK', 'Aleutians West', 'Aleutians West Census Area, AK', 'coming_soon', 0),
('ak-anchorage', 'AK', 'Anchorage', 'Anchorage Municipality, AK', 'coming_soon', 0),
('ak-bethel', 'AK', 'Bethel', 'Bethel Census Area, AK', 'coming_soon', 0),
('ak-bristol-bay', 'AK', 'Bristol Bay', 'Bristol Bay Borough, AK', 'coming_soon', 0),
('ak-chugach', 'AK', 'Chugach', 'Chugach Census Area, AK', 'coming_soon', 0),
('ak-copper-river', 'AK', 'Copper River', 'Copper River Census Area, AK', 'coming_soon', 0),
('ak-denali', 'AK', 'Denali', 'Denali Borough, AK', 'coming_soon', 0),
('ak-dillingham', 'AK', 'Dillingham', 'Dillingham Census Area, AK', 'coming_soon', 0),
('ak-fairbanks-north-star', 'AK', 'Fairbanks North Star', 'Fairbanks North Star Borough, AK', 'coming_soon', 0),
('ak-haines', 'AK', 'Haines', 'Haines Borough, AK', 'coming_soon', 0),
('ak-hoonah-angoon', 'AK', 'Hoonah-Angoon', 'Hoonah-Angoon Census Area, AK', 'coming_soon', 0),
('ak-juneau', 'AK', 'Juneau', 'Juneau City and Borough, AK', 'coming_soon', 0),
('ak-kenai-peninsula', 'AK', 'Kenai Peninsula', 'Kenai Peninsula Borough, AK', 'coming_soon', 0),
('ak-ketchikan-gateway', 'AK', 'Ketchikan Gateway', 'Ketchikan Gateway Borough, AK', 'coming_soon', 0),
('ak-kodiak-island', 'AK', 'Kodiak Island', 'Kodiak Island Borough, AK', 'coming_soon', 0),
('ak-kusilvak', 'AK', 'Kusilvak', 'Kusilvak Census Area, AK', 'coming_soon', 0),
('ak-lake-and-peninsula', 'AK', 'Lake and Peninsula', 'Lake and Peninsula Borough, AK', 'coming_soon', 0),
('ak-matanuska-susitna', 'AK', 'Matanuska-Susitna', 'Matanuska-Susitna Borough, AK', 'coming_soon', 0),
('ak-nome', 'AK', 'Nome', 'Nome Census Area, AK', 'coming_soon', 0),
('ak-north-slope', 'AK', 'North Slope', 'North Slope Borough, AK', 'coming_soon', 0),
('ak-northwest-arctic', 'AK', 'Northwest Arctic', 'Northwest Arctic Borough, AK', 'coming_soon', 0),
('ak-petersburg', 'AK', 'Petersburg', 'Petersburg Borough, AK', 'coming_soon', 0),
('ak-prince-of-wales-hyder', 'AK', 'Prince of Wales-Hyder', 'Prince of Wales-Hyder Census Area, AK', 'coming_soon', 0),
('ak-sitka', 'AK', 'Sitka', 'Sitka City and Borough, AK', 'coming_soon', 0),
('ak-skagway', 'AK', 'Skagway', 'Skagway Municipality, AK', 'coming_soon', 0),
('ak-southeast-fairbanks', 'AK', 'Southeast Fairbanks', 'Southeast Fairbanks Census Area, AK', 'coming_soon', 0),
('ak-wrangell', 'AK', 'Wrangell', 'Wrangell City and Borough, AK', 'coming_soon', 0),
('ak-yakutat', 'AK', 'Yakutat', 'Yakutat City and Borough, AK', 'coming_soon', 0),
('ak-yukon-koyukuk', 'AK', 'Yukon-Koyukuk', 'Yukon-Koyukuk Census Area, AK', 'coming_soon', 0),

-- Arizona (15 counties)
('az-apache', 'AZ', 'Apache', 'Apache County, AZ', 'coming_soon', 0),
('az-cochise', 'AZ', 'Cochise', 'Cochise County, AZ', 'coming_soon', 0),
('az-coconino', 'AZ', 'Coconino', 'Coconino County, AZ', 'coming_soon', 0),
('az-gila', 'AZ', 'Gila', 'Gila County, AZ', 'coming_soon', 0),
('az-graham', 'AZ', 'Graham', 'Graham County, AZ', 'coming_soon', 0),
('az-greenlee', 'AZ', 'Greenlee', 'Greenlee County, AZ', 'coming_soon', 0),
('az-la-paz', 'AZ', 'La Paz', 'La Paz County, AZ', 'coming_soon', 0),
('az-maricopa', 'AZ', 'Maricopa', 'Maricopa County, AZ', 'coming_soon', 0),
('az-mohave', 'AZ', 'Mohave', 'Mohave County, AZ', 'coming_soon', 0),
('az-navajo', 'AZ', 'Navajo', 'Navajo County, AZ', 'coming_soon', 0),
('az-pima', 'AZ', 'Pima', 'Pima County, AZ', 'coming_soon', 0),
('az-pinal', 'AZ', 'Pinal', 'Pinal County, AZ', 'coming_soon', 0),
('az-santa-cruz', 'AZ', 'Santa Cruz', 'Santa Cruz County, AZ', 'coming_soon', 0),
('az-yavapai', 'AZ', 'Yavapai', 'Yavapai County, AZ', 'coming_soon', 0),
('az-yuma', 'AZ', 'Yuma', 'Yuma County, AZ', 'coming_soon', 0),

-- Arkansas (75 counties)
('ar-arkansas', 'AR', 'Arkansas', 'Arkansas County, AR', 'coming_soon', 0),
('ar-ashley', 'AR', 'Ashley', 'Ashley County, AR', 'coming_soon', 0),
('ar-baxter', 'AR', 'Baxter', 'Baxter County, AR', 'coming_soon', 0),
('ar-benton', 'AR', 'Benton', 'Benton County, AR', 'coming_soon', 0),
('ar-boone', 'AR', 'Boone', 'Boone County, AR', 'coming_soon', 0),
('ar-bradley', 'AR', 'Bradley', 'Bradley County, AR', 'coming_soon', 0),
('ar-calhoun', 'AR', 'Calhoun', 'Calhoun County, AR', 'coming_soon', 0),
('ar-carroll', 'AR', 'Carroll', 'Carroll County, AR', 'coming_soon', 0),
('ar-chicot', 'AR', 'Chicot', 'Chicot County, AR', 'coming_soon', 0),
('ar-clark', 'AR', 'Clark', 'Clark County, AR', 'coming_soon', 0),
('ar-clay', 'AR', 'Clay', 'Clay County, AR', 'coming_soon', 0),
('ar-cleburne', 'AR', 'Cleburne', 'Cleburne County, AR', 'coming_soon', 0),
('ar-cleveland', 'AR', 'Cleveland', 'Cleveland County, AR', 'coming_soon', 0),
('ar-columbia', 'AR', 'Columbia', 'Columbia County, AR', 'coming_soon', 0),
('ar-conway', 'AR', 'Conway', 'Conway County, AR', 'coming_soon', 0),
('ar-craighead', 'AR', 'Craighead', 'Craighead County, AR', 'coming_soon', 0),
('ar-crawford', 'AR', 'Crawford', 'Crawford County, AR', 'coming_soon', 0),
('ar-crittenden', 'AR', 'Crittenden', 'Crittenden County, AR', 'coming_soon', 0),
('ar-cross', 'AR', 'Cross', 'Cross County, AR', 'coming_soon', 0),
('ar-dallas', 'AR', 'Dallas', 'Dallas County, AR', 'coming_soon', 0),
('ar-desha', 'AR', 'Desha', 'Desha County, AR', 'coming_soon', 0),
('ar-drew', 'AR', 'Drew', 'Drew County, AR', 'coming_soon', 0),
('ar-faulkner', 'AR', 'Faulkner', 'Faulkner County, AR', 'coming_soon', 0),
('ar-franklin', 'AR', 'Franklin', 'Franklin County, AR', 'coming_soon', 0),
('ar-fulton', 'AR', 'Fulton', 'Fulton County, AR', 'coming_soon', 0),
('ar-garland', 'AR', 'Garland', 'Garland County, AR', 'coming_soon', 0),
('ar-grant', 'AR', 'Grant', 'Grant County, AR', 'coming_soon', 0),
('ar-greene', 'AR', 'Greene', 'Greene County, AR', 'coming_soon', 0),
('ar-hempstead', 'AR', 'Hempstead', 'Hempstead County, AR', 'coming_soon', 0),
('ar-hot-spring', 'AR', 'Hot Spring', 'Hot Spring County, AR', 'coming_soon', 0),
('ar-howard', 'AR', 'Howard', 'Howard County, AR', 'coming_soon', 0),
('ar-independence', 'AR', 'Independence', 'Independence County, AR', 'coming_soon', 0),
('ar-izard', 'AR', 'Izard', 'Izard County, AR', 'coming_soon', 0),
('ar-jackson', 'AR', 'Jackson', 'Jackson County, AR', 'coming_soon', 0),
('ar-jefferson', 'AR', 'Jefferson', 'Jefferson County, AR', 'coming_soon', 0),
('ar-johnson', 'AR', 'Johnson', 'Johnson County, AR', 'coming_soon', 0),
('ar-lafayette', 'AR', 'Lafayette', 'Lafayette County, AR', 'coming_soon', 0),
('ar-lawrence', 'AR', 'Lawrence', 'Lawrence County, AR', 'coming_soon', 0),
('ar-lee', 'AR', 'Lee', 'Lee County, AR', 'coming_soon', 0),
('ar-lincoln', 'AR', 'Lincoln', 'Lincoln County, AR', 'coming_soon', 0),
('ar-little-river', 'AR', 'Little River', 'Little River County, AR', 'coming_soon', 0),
('ar-logan', 'AR', 'Logan', 'Logan County, AR', 'coming_soon', 0),
('ar-lonoke', 'AR', 'Lonoke', 'Lonoke County, AR', 'coming_soon', 0),
('ar-madison', 'AR', 'Madison', 'Madison County, AR', 'coming_soon', 0),
('ar-marion', 'AR', 'Marion', 'Marion County, AR', 'coming_soon', 0),
('ar-miller', 'AR', 'Miller', 'Miller County, AR', 'coming_soon', 0),
('ar-mississippi', 'AR', 'Mississippi', 'Mississippi County, AR', 'coming_soon', 0),
('ar-monroe', 'AR', 'Monroe', 'Monroe County, AR', 'coming_soon', 0),
('ar-montgomery', 'AR', 'Montgomery', 'Montgomery County, AR', 'coming_soon', 0),
('ar-nevada', 'AR', 'Nevada', 'Nevada County, AR', 'coming_soon', 0),
('ar-newton', 'AR', 'Newton', 'Newton County, AR', 'coming_soon', 0),
('ar-ouachita', 'AR', 'Ouachita', 'Ouachita County, AR', 'coming_soon', 0),
('ar-perry', 'AR', 'Perry', 'Perry County, AR', 'coming_soon', 0),
('ar-phillips', 'AR', 'Phillips', 'Phillips County, AR', 'coming_soon', 0),
('ar-pike', 'AR', 'Pike', 'Pike County, AR', 'coming_soon', 0),
('ar-poinsett', 'AR', 'Poinsett', 'Poinsett County, AR', 'coming_soon', 0),
('ar-polk', 'AR', 'Polk', 'Polk County, AR', 'coming_soon', 0),
('ar-pope', 'AR', 'Pope', 'Pope County, AR', 'coming_soon', 0),
('ar-prairie', 'AR', 'Prairie', 'Prairie County, AR', 'coming_soon', 0),
('ar-pulaski', 'AR', 'Pulaski', 'Pulaski County, AR', 'coming_soon', 0),
('ar-randolph', 'AR', 'Randolph', 'Randolph County, AR', 'coming_soon', 0),
('ar-saline', 'AR', 'Saline', 'Saline County, AR', 'coming_soon', 0),
('ar-scott', 'AR', 'Scott', 'Scott County, AR', 'coming_soon', 0),
('ar-searcy', 'AR', 'Searcy', 'Searcy County, AR', 'coming_soon', 0),
('ar-sebastian', 'AR', 'Sebastian', 'Sebastian County, AR', 'coming_soon', 0),
('ar-sevier', 'AR', 'Sevier', 'Sevier County, AR', 'coming_soon', 0),
('ar-sharp', 'AR', 'Sharp', 'Sharp County, AR', 'coming_soon', 0),
('ar-st-francis', 'AR', 'St. Francis', 'St. Francis County, AR', 'coming_soon', 0),
('ar-stone', 'AR', 'Stone', 'Stone County, AR', 'coming_soon', 0),
('ar-union', 'AR', 'Union', 'Union County, AR', 'coming_soon', 0),
('ar-van-buren', 'AR', 'Van Buren', 'Van Buren County, AR', 'coming_soon', 0),
('ar-washington', 'AR', 'Washington', 'Washington County, AR', 'coming_soon', 0),
('ar-white', 'AR', 'White', 'White County, AR', 'coming_soon', 0),
('ar-woodruff', 'AR', 'Woodruff', 'Woodruff County, AR', 'coming_soon', 0),
('ar-yell', 'AR', 'Yell', 'Yell County, AR', 'coming_soon', 0),

-- California (58 counties)
('ca-alameda', 'CA', 'Alameda', 'Alameda County, CA', 'coming_soon', 0),
('ca-alpine', 'CA', 'Alpine', 'Alpine County, CA', 'coming_soon', 0),
('ca-amador', 'CA', 'Amador', 'Amador County, CA', 'coming_soon', 0),
('ca-butte', 'CA', 'Butte', 'Butte County, CA', 'coming_soon', 0),
('ca-calaveras', 'CA', 'Calaveras', 'Calaveras County, CA', 'coming_soon', 0),
('ca-colusa', 'CA', 'Colusa', 'Colusa County, CA', 'coming_soon', 0),
('ca-contra-costa', 'CA', 'Contra Costa', 'Contra Costa County, CA', 'coming_soon', 0),
('ca-del-norte', 'CA', 'Del Norte', 'Del Norte County, CA', 'coming_soon', 0),
('ca-el-dorado', 'CA', 'El Dorado', 'El Dorado County, CA', 'coming_soon', 0),
('ca-fresno', 'CA', 'Fresno', 'Fresno County, CA', 'coming_soon', 0),
('ca-glenn', 'CA', 'Glenn', 'Glenn County, CA', 'coming_soon', 0),
('ca-humboldt', 'CA', 'Humboldt', 'Humboldt County, CA', 'coming_soon', 0),
('ca-imperial', 'CA', 'Imperial', 'Imperial County, CA', 'coming_soon', 0),
('ca-inyo', 'CA', 'Inyo', 'Inyo County, CA', 'coming_soon', 0),
('ca-kern', 'CA', 'Kern', 'Kern County, CA', 'coming_soon', 0),
('ca-kings', 'CA', 'Kings', 'Kings County, CA', 'coming_soon', 0),
('ca-lake', 'CA', 'Lake', 'Lake County, CA', 'coming_soon', 0),
('ca-lassen', 'CA', 'Lassen', 'Lassen County, CA', 'coming_soon', 0),
('ca-los-angeles', 'CA', 'Los Angeles', 'Los Angeles County, CA', 'coming_soon', 0),
('ca-madera', 'CA', 'Madera', 'Madera County, CA', 'coming_soon', 0),
('ca-marin', 'CA', 'Marin', 'Marin County, CA', 'coming_soon', 0),
('ca-mariposa', 'CA', 'Mariposa', 'Mariposa County, CA', 'coming_soon', 0),
('ca-mendocino', 'CA', 'Mendocino', 'Mendocino County, CA', 'coming_soon', 0),
('ca-merced', 'CA', 'Merced', 'Merced County, CA', 'coming_soon', 0),
('ca-modoc', 'CA', 'Modoc', 'Modoc County, CA', 'coming_soon', 0),
('ca-mono', 'CA', 'Mono', 'Mono County, CA', 'coming_soon', 0),
('ca-monterey', 'CA', 'Monterey', 'Monterey County, CA', 'coming_soon', 0),
('ca-napa', 'CA', 'Napa', 'Napa County, CA', 'coming_soon', 0),
('ca-nevada', 'CA', 'Nevada', 'Nevada County, CA', 'coming_soon', 0),
('ca-orange', 'CA', 'Orange', 'Orange County, CA', 'coming_soon', 0),
('ca-placer', 'CA', 'Placer', 'Placer County, CA', 'coming_soon', 0),
('ca-plumas', 'CA', 'Plumas', 'Plumas County, CA', 'coming_soon', 0),
('ca-riverside', 'CA', 'Riverside', 'Riverside County, CA', 'coming_soon', 0),
('ca-sacramento', 'CA', 'Sacramento', 'Sacramento County, CA', 'coming_soon', 0),
('ca-san-benito', 'CA', 'San Benito', 'San Benito County, CA', 'coming_soon', 0),
('ca-san-bernardino', 'CA', 'San Bernardino', 'San Bernardino County, CA', 'coming_soon', 0),
('ca-san-diego', 'CA', 'San Diego', 'San Diego County, CA', 'coming_soon', 0),
('ca-san-francisco', 'CA', 'San Francisco', 'San Francisco County, CA', 'coming_soon', 0),
('ca-san-joaquin', 'CA', 'San Joaquin', 'San Joaquin County, CA', 'coming_soon', 0),
('ca-san-luis-obispo', 'CA', 'San Luis Obispo', 'San Luis Obispo County, CA', 'coming_soon', 0),
('ca-san-mateo', 'CA', 'San Mateo', 'San Mateo County, CA', 'coming_soon', 0),
('ca-santa-barbara', 'CA', 'Santa Barbara', 'Santa Barbara County, CA', 'coming_soon', 0),
('ca-santa-clara', 'CA', 'Santa Clara', 'Santa Clara County, CA', 'coming_soon', 0),
('ca-santa-cruz', 'CA', 'Santa Cruz', 'Santa Cruz County, CA', 'coming_soon', 0),
('ca-shasta', 'CA', 'Shasta', 'Shasta County, CA', 'coming_soon', 0),
('ca-sierra', 'CA', 'Sierra', 'Sierra County, CA', 'coming_soon', 0),
('ca-siskiyou', 'CA', 'Siskiyou', 'Siskiyou County, CA', 'coming_soon', 0),
('ca-solano', 'CA', 'Solano', 'Solano County, CA', 'coming_soon', 0),
('ca-sonoma', 'CA', 'Sonoma', 'Sonoma County, CA', 'coming_soon', 0),
('ca-stanislaus', 'CA', 'Stanislaus', 'Stanislaus County, CA', 'coming_soon', 0),
('ca-sutter', 'CA', 'Sutter', 'Sutter County, CA', 'coming_soon', 0),
('ca-tehama', 'CA', 'Tehama', 'Tehama County, CA', 'coming_soon', 0),
('ca-trinity', 'CA', 'Trinity', 'Trinity County, CA', 'coming_soon', 0),
('ca-tulare', 'CA', 'Tulare', 'Tulare County, CA', 'coming_soon', 0),
('ca-tuolumne', 'CA', 'Tuolumne', 'Tuolumne County, CA', 'coming_soon', 0),
('ca-ventura', 'CA', 'Ventura', 'Ventura County, CA', 'coming_soon', 0),
('ca-yolo', 'CA', 'Yolo', 'Yolo County, CA', 'coming_soon', 0),
('ca-yuba', 'CA', 'Yuba', 'Yuba County, CA', 'coming_soon', 0),

-- Colorado (64 counties)
('co-adams', 'CO', 'Adams', 'Adams County, CO', 'coming_soon', 0),
('co-alamosa', 'CO', 'Alamosa', 'Alamosa County, CO', 'coming_soon', 0),
('co-arapahoe', 'CO', 'Arapahoe', 'Arapahoe County, CO', 'coming_soon', 0),
('co-archuleta', 'CO', 'Archuleta', 'Archuleta County, CO', 'coming_soon', 0),
('co-baca', 'CO', 'Baca', 'Baca County, CO', 'coming_soon', 0),
('co-bent', 'CO', 'Bent', 'Bent County, CO', 'coming_soon', 0),
('co-boulder', 'CO', 'Boulder', 'Boulder County, CO', 'coming_soon', 0),
('co-broomfield', 'CO', 'Broomfield', 'Broomfield County, CO', 'coming_soon', 0),
('co-chaffee', 'CO', 'Chaffee', 'Chaffee County, CO', 'coming_soon', 0),
('co-cheyenne', 'CO', 'Cheyenne', 'Cheyenne County, CO', 'coming_soon', 0),
('co-clear-creek', 'CO', 'Clear Creek', 'Clear Creek County, CO', 'coming_soon', 0),
('co-conejos', 'CO', 'Conejos', 'Conejos County, CO', 'coming_soon', 0),
('co-costilla', 'CO', 'Costilla', 'Costilla County, CO', 'coming_soon', 0),
('co-crowley', 'CO', 'Crowley', 'Crowley County, CO', 'coming_soon', 0),
('co-custer', 'CO', 'Custer', 'Custer County, CO', 'coming_soon', 0),
('co-delta', 'CO', 'Delta', 'Delta County, CO', 'coming_soon', 0),
('co-denver', 'CO', 'Denver', 'Denver County, CO', 'coming_soon', 0),
('co-dolores', 'CO', 'Dolores', 'Dolores County, CO', 'coming_soon', 0),
('co-douglas', 'CO', 'Douglas', 'Douglas County, CO', 'coming_soon', 0),
('co-eagle', 'CO', 'Eagle', 'Eagle County, CO', 'coming_soon', 0),
('co-el-paso', 'CO', 'El Paso', 'El Paso County, CO', 'coming_soon', 0),
('co-elbert', 'CO', 'Elbert', 'Elbert County, CO', 'coming_soon', 0),
('co-fremont', 'CO', 'Fremont', 'Fremont County, CO', 'coming_soon', 0),
('co-garfield', 'CO', 'Garfield', 'Garfield County, CO', 'coming_soon', 0),
('co-gilpin', 'CO', 'Gilpin', 'Gilpin County, CO', 'coming_soon', 0),
('co-grand', 'CO', 'Grand', 'Grand County, CO', 'coming_soon', 0),
('co-gunnison', 'CO', 'Gunnison', 'Gunnison County, CO', 'coming_soon', 0),
('co-hinsdale', 'CO', 'Hinsdale', 'Hinsdale County, CO', 'coming_soon', 0),
('co-huerfano', 'CO', 'Huerfano', 'Huerfano County, CO', 'coming_soon', 0),
('co-jackson', 'CO', 'Jackson', 'Jackson County, CO', 'coming_soon', 0),
('co-jefferson', 'CO', 'Jefferson', 'Jefferson County, CO', 'coming_soon', 0),
('co-kiowa', 'CO', 'Kiowa', 'Kiowa County, CO', 'coming_soon', 0),
('co-kit-carson', 'CO', 'Kit Carson', 'Kit Carson County, CO', 'coming_soon', 0),
('co-la-plata', 'CO', 'La Plata', 'La Plata County, CO', 'coming_soon', 0),
('co-lake', 'CO', 'Lake', 'Lake County, CO', 'coming_soon', 0),
('co-larimer', 'CO', 'Larimer', 'Larimer County, CO', 'coming_soon', 0),
('co-las-animas', 'CO', 'Las Animas', 'Las Animas County, CO', 'coming_soon', 0),
('co-lincoln', 'CO', 'Lincoln', 'Lincoln County, CO', 'coming_soon', 0),
('co-logan', 'CO', 'Logan', 'Logan County, CO', 'coming_soon', 0),
('co-mesa', 'CO', 'Mesa', 'Mesa County, CO', 'coming_soon', 0),
('co-mineral', 'CO', 'Mineral', 'Mineral County, CO', 'coming_soon', 0),
('co-moffat', 'CO', 'Moffat', 'Moffat County, CO', 'coming_soon', 0),
('co-montezuma', 'CO', 'Montezuma', 'Montezuma County, CO', 'coming_soon', 0),
('co-montrose', 'CO', 'Montrose', 'Montrose County, CO', 'coming_soon', 0),
('co-morgan', 'CO', 'Morgan', 'Morgan County, CO', 'coming_soon', 0),
('co-otero', 'CO', 'Otero', 'Otero County, CO', 'coming_soon', 0),
('co-ouray', 'CO', 'Ouray', 'Ouray County, CO', 'coming_soon', 0),
('co-park', 'CO', 'Park', 'Park County, CO', 'coming_soon', 0),
('co-phillips', 'CO', 'Phillips', 'Phillips County, CO', 'coming_soon', 0),
('co-pitkin', 'CO', 'Pitkin', 'Pitkin County, CO', 'coming_soon', 0),
('co-prowers', 'CO', 'Prowers', 'Prowers County, CO', 'coming_soon', 0),
('co-pueblo', 'CO', 'Pueblo', 'Pueblo County, CO', 'coming_soon', 0),
('co-rio-blanco', 'CO', 'Rio Blanco', 'Rio Blanco County, CO', 'coming_soon', 0),
('co-rio-grande', 'CO', 'Rio Grande', 'Rio Grande County, CO', 'coming_soon', 0),
('co-routt', 'CO', 'Routt', 'Routt County, CO', 'coming_soon', 0),
('co-saguache', 'CO', 'Saguache', 'Saguache County, CO', 'coming_soon', 0),
('co-san-juan', 'CO', 'San Juan', 'San Juan County, CO', 'coming_soon', 0),
('co-san-miguel', 'CO', 'San Miguel', 'San Miguel County, CO', 'coming_soon', 0),
('co-sedgwick', 'CO', 'Sedgwick', 'Sedgwick County, CO', 'coming_soon', 0),
('co-summit', 'CO', 'Summit', 'Summit County, CO', 'coming_soon', 0),
('co-teller', 'CO', 'Teller', 'Teller County, CO', 'coming_soon', 0),
('co-washington', 'CO', 'Washington', 'Washington County, CO', 'coming_soon', 0),
('co-weld', 'CO', 'Weld', 'Weld County, CO', 'coming_soon', 0),
('co-yuma', 'CO', 'Yuma', 'Yuma County, CO', 'coming_soon', 0),

-- Connecticut (8 counties)
('ct-fairfield', 'CT', 'Fairfield', 'Fairfield County, CT', 'coming_soon', 0),
('ct-hartford', 'CT', 'Hartford', 'Hartford County, CT', 'coming_soon', 0),
('ct-litchfield', 'CT', 'Litchfield', 'Litchfield County, CT', 'coming_soon', 0),
('ct-middlesex', 'CT', 'Middlesex', 'Middlesex County, CT', 'coming_soon', 0),
('ct-new-haven', 'CT', 'New Haven', 'New Haven County, CT', 'coming_soon', 0),
('ct-new-london', 'CT', 'New London', 'New London County, CT', 'coming_soon', 0),
('ct-tolland', 'CT', 'Tolland', 'Tolland County, CT', 'coming_soon', 0),
('ct-windham', 'CT', 'Windham', 'Windham County, CT', 'coming_soon', 0),

-- Delaware (3 counties)
('de-kent', 'DE', 'Kent', 'Kent County, DE', 'coming_soon', 0),
('de-new-castle', 'DE', 'New Castle', 'New Castle County, DE', 'coming_soon', 0),
('de-sussex', 'DE', 'Sussex', 'Sussex County, DE', 'coming_soon', 0),

-- Florida (67 counties)
('fl-alachua', 'FL', 'Alachua', 'Alachua County, FL', 'coming_soon', 0),
('fl-baker', 'FL', 'Baker', 'Baker County, FL', 'coming_soon', 0),
('fl-bay', 'FL', 'Bay', 'Bay County, FL', 'coming_soon', 0),
('fl-bradford', 'FL', 'Bradford', 'Bradford County, FL', 'coming_soon', 0),
('fl-brevard', 'FL', 'Brevard', 'Brevard County, FL', 'coming_soon', 0),
('fl-broward', 'FL', 'Broward', 'Broward County, FL', 'coming_soon', 0),
('fl-calhoun', 'FL', 'Calhoun', 'Calhoun County, FL', 'coming_soon', 0),
('fl-charlotte', 'FL', 'Charlotte', 'Charlotte County, FL', 'coming_soon', 0),
('fl-citrus', 'FL', 'Citrus', 'Citrus County, FL', 'coming_soon', 0),
('fl-clay', 'FL', 'Clay', 'Clay County, FL', 'coming_soon', 0),
('fl-collier', 'FL', 'Collier', 'Collier County, FL', 'coming_soon', 0),
('fl-columbia', 'FL', 'Columbia', 'Columbia County, FL', 'coming_soon', 0),
('fl-desoto', 'FL', 'DeSoto', 'DeSoto County, FL', 'coming_soon', 0),
('fl-dixie', 'FL', 'Dixie', 'Dixie County, FL', 'coming_soon', 0),
('fl-duval', 'FL', 'Duval', 'Duval County, FL', 'coming_soon', 0),
('fl-escambia', 'FL', 'Escambia', 'Escambia County, FL', 'coming_soon', 0),
('fl-flagler', 'FL', 'Flagler', 'Flagler County, FL', 'coming_soon', 0),
('fl-franklin', 'FL', 'Franklin', 'Franklin County, FL', 'coming_soon', 0),
('fl-gadsden', 'FL', 'Gadsden', 'Gadsden County, FL', 'coming_soon', 0),
('fl-gilchrist', 'FL', 'Gilchrist', 'Gilchrist County, FL', 'coming_soon', 0),
('fl-glades', 'FL', 'Glades', 'Glades County, FL', 'coming_soon', 0),
('fl-gulf', 'FL', 'Gulf', 'Gulf County, FL', 'coming_soon', 0),
('fl-hamilton', 'FL', 'Hamilton', 'Hamilton County, FL', 'coming_soon', 0),
('fl-hardee', 'FL', 'Hardee', 'Hardee County, FL', 'coming_soon', 0),
('fl-hendry', 'FL', 'Hendry', 'Hendry County, FL', 'coming_soon', 0),
('fl-hernando', 'FL', 'Hernando', 'Hernando County, FL', 'coming_soon', 0),
('fl-highlands', 'FL', 'Highlands', 'Highlands County, FL', 'coming_soon', 0),
('fl-hillsborough', 'FL', 'Hillsborough', 'Hillsborough County, FL', 'coming_soon', 0),
('fl-holmes', 'FL', 'Holmes', 'Holmes County, FL', 'coming_soon', 0),
('fl-indian-river', 'FL', 'Indian River', 'Indian River County, FL', 'coming_soon', 0),
('fl-jackson', 'FL', 'Jackson', 'Jackson County, FL', 'coming_soon', 0),
('fl-jefferson', 'FL', 'Jefferson', 'Jefferson County, FL', 'coming_soon', 0),
('fl-lafayette', 'FL', 'Lafayette', 'Lafayette County, FL', 'coming_soon', 0),
('fl-lake', 'FL', 'Lake', 'Lake County, FL', 'coming_soon', 0),
('fl-lee', 'FL', 'Lee', 'Lee County, FL', 'coming_soon', 0),
('fl-leon', 'FL', 'Leon', 'Leon County, FL', 'coming_soon', 0),
('fl-levy', 'FL', 'Levy', 'Levy County, FL', 'coming_soon', 0),
('fl-liberty', 'FL', 'Liberty', 'Liberty County, FL', 'coming_soon', 0),
('fl-madison', 'FL', 'Madison', 'Madison County, FL', 'coming_soon', 0),
('fl-manatee', 'FL', 'Manatee', 'Manatee County, FL', 'coming_soon', 0),
('fl-marion', 'FL', 'Marion', 'Marion County, FL', 'coming_soon', 0),
('fl-martin', 'FL', 'Martin', 'Martin County, FL', 'coming_soon', 0),
('fl-miami-dade', 'FL', 'Miami-Dade', 'Miami-Dade County, FL', 'coming_soon', 0),
('fl-monroe', 'FL', 'Monroe', 'Monroe County, FL', 'coming_soon', 0),
('fl-nassau', 'FL', 'Nassau', 'Nassau County, FL', 'coming_soon', 0),
('fl-okaloosa', 'FL', 'Okaloosa', 'Okaloosa County, FL', 'coming_soon', 0),
('fl-okeechobee', 'FL', 'Okeechobee', 'Okeechobee County, FL', 'coming_soon', 0),
('fl-orange', 'FL', 'Orange', 'Orange County, FL', 'coming_soon', 0),
('fl-osceola', 'FL', 'Osceola', 'Osceola County, FL', 'coming_soon', 0),
('fl-palm-beach', 'FL', 'Palm Beach', 'Palm Beach County, FL', 'coming_soon', 0),
('fl-pasco', 'FL', 'Pasco', 'Pasco County, FL', 'coming_soon', 0),
('fl-pinellas', 'FL', 'Pinellas', 'Pinellas County, FL', 'coming_soon', 0),
('fl-polk', 'FL', 'Polk', 'Polk County, FL', 'coming_soon', 0),
('fl-putnam', 'FL', 'Putnam', 'Putnam County, FL', 'coming_soon', 0),
('fl-santa-rosa', 'FL', 'Santa Rosa', 'Santa Rosa County, FL', 'coming_soon', 0),
('fl-sarasota', 'FL', 'Sarasota', 'Sarasota County, FL', 'coming_soon', 0),
('fl-seminole', 'FL', 'Seminole', 'Seminole County, FL', 'coming_soon', 0),
('fl-st-johns', 'FL', 'St. Johns', 'St. Johns County, FL', 'coming_soon', 0),
('fl-st-lucie', 'FL', 'St. Lucie', 'St. Lucie County, FL', 'coming_soon', 0),
('fl-sumter', 'FL', 'Sumter', 'Sumter County, FL', 'coming_soon', 0),
('fl-suwannee', 'FL', 'Suwannee', 'Suwannee County, FL', 'coming_soon', 0),
('fl-taylor', 'FL', 'Taylor', 'Taylor County, FL', 'coming_soon', 0),
('fl-union', 'FL', 'Union', 'Union County, FL', 'coming_soon', 0),
('fl-volusia', 'FL', 'Volusia', 'Volusia County, FL', 'coming_soon', 0),
('fl-wakulla', 'FL', 'Wakulla', 'Wakulla County, FL', 'coming_soon', 0),
('fl-walton', 'FL', 'Walton', 'Walton County, FL', 'coming_soon', 0),
('fl-washington', 'FL', 'Washington', 'Washington County, FL', 'coming_soon', 0),

-- Georgia (159 counties)
('ga-appling', 'GA', 'Appling', 'Appling County, GA', 'coming_soon', 0),
('ga-atkinson', 'GA', 'Atkinson', 'Atkinson County, GA', 'coming_soon', 0),
('ga-bacon', 'GA', 'Bacon', 'Bacon County, GA', 'coming_soon', 0),
('ga-baker', 'GA', 'Baker', 'Baker County, GA', 'coming_soon', 0),
('ga-baldwin', 'GA', 'Baldwin', 'Baldwin County, GA', 'coming_soon', 0),
('ga-banks', 'GA', 'Banks', 'Banks County, GA', 'coming_soon', 0),
('ga-barrow', 'GA', 'Barrow', 'Barrow County, GA', 'coming_soon', 0),
('ga-bartow', 'GA', 'Bartow', 'Bartow County, GA', 'coming_soon', 0),
('ga-ben-hill', 'GA', 'Ben Hill', 'Ben Hill County, GA', 'coming_soon', 0),
('ga-berrien', 'GA', 'Berrien', 'Berrien County, GA', 'coming_soon', 0),
('ga-bibb', 'GA', 'Bibb', 'Bibb County, GA', 'coming_soon', 0),
('ga-bleckley', 'GA', 'Bleckley', 'Bleckley County, GA', 'coming_soon', 0),
('ga-brantley', 'GA', 'Brantley', 'Brantley County, GA', 'coming_soon', 0),
('ga-brooks', 'GA', 'Brooks', 'Brooks County, GA', 'coming_soon', 0),
('ga-bryan', 'GA', 'Bryan', 'Bryan County, GA', 'coming_soon', 0),
('ga-bulloch', 'GA', 'Bulloch', 'Bulloch County, GA', 'coming_soon', 0),
('ga-burke', 'GA', 'Burke', 'Burke County, GA', 'coming_soon', 0),
('ga-butts', 'GA', 'Butts', 'Butts County, GA', 'coming_soon', 0),
('ga-calhoun', 'GA', 'Calhoun', 'Calhoun County, GA', 'coming_soon', 0),
('ga-camden', 'GA', 'Camden', 'Camden County, GA', 'coming_soon', 0),
('ga-candler', 'GA', 'Candler', 'Candler County, GA', 'coming_soon', 0),
('ga-carroll', 'GA', 'Carroll', 'Carroll County, GA', 'coming_soon', 0),
('ga-catoosa', 'GA', 'Catoosa', 'Catoosa County, GA', 'coming_soon', 0),
('ga-charlton', 'GA', 'Charlton', 'Charlton County, GA', 'coming_soon', 0),
('ga-chatham', 'GA', 'Chatham', 'Chatham County, GA', 'coming_soon', 0),
('ga-chattahoochee', 'GA', 'Chattahoochee', 'Chattahoochee County, GA', 'coming_soon', 0),
('ga-chattooga', 'GA', 'Chattooga', 'Chattooga County, GA', 'coming_soon', 0),
('ga-cherokee', 'GA', 'Cherokee', 'Cherokee County, GA', 'coming_soon', 0),
('ga-clarke', 'GA', 'Clarke', 'Clarke County, GA', 'coming_soon', 0),
('ga-clay', 'GA', 'Clay', 'Clay County, GA', 'coming_soon', 0),
('ga-clayton', 'GA', 'Clayton', 'Clayton County, GA', 'coming_soon', 0),
('ga-clinch', 'GA', 'Clinch', 'Clinch County, GA', 'coming_soon', 0),
('ga-cobb', 'GA', 'Cobb', 'Cobb County, GA', 'coming_soon', 0),
('ga-coffee', 'GA', 'Coffee', 'Coffee County, GA', 'coming_soon', 0),
('ga-colquitt', 'GA', 'Colquitt', 'Colquitt County, GA', 'coming_soon', 0),
('ga-columbia', 'GA', 'Columbia', 'Columbia County, GA', 'coming_soon', 0),
('ga-cook', 'GA', 'Cook', 'Cook County, GA', 'coming_soon', 0),
('ga-coweta', 'GA', 'Coweta', 'Coweta County, GA', 'coming_soon', 0),
('ga-crawford', 'GA', 'Crawford', 'Crawford County, GA', 'coming_soon', 0),
('ga-crisp', 'GA', 'Crisp', 'Crisp County, GA', 'coming_soon', 0),
('ga-dade', 'GA', 'Dade', 'Dade County, GA', 'coming_soon', 0),
('ga-dawson', 'GA', 'Dawson', 'Dawson County, GA', 'coming_soon', 0),
('ga-decatur', 'GA', 'Decatur', 'Decatur County, GA', 'coming_soon', 0),
('ga-dekalb', 'GA', 'DeKalb', 'DeKalb County, GA', 'coming_soon', 0),
('ga-dodge', 'GA', 'Dodge', 'Dodge County, GA', 'coming_soon', 0),
('ga-dooly', 'GA', 'Dooly', 'Dooly County, GA', 'coming_soon', 0),
('ga-dougherty', 'GA', 'Dougherty', 'Dougherty County, GA', 'coming_soon', 0),
('ga-douglas', 'GA', 'Douglas', 'Douglas County, GA', 'coming_soon', 0),
('ga-early', 'GA', 'Early', 'Early County, GA', 'coming_soon', 0),
('ga-echols', 'GA', 'Echols', 'Echols County, GA', 'coming_soon', 0),
('ga-effingham', 'GA', 'Effingham', 'Effingham County, GA', 'coming_soon', 0),
('ga-elbert', 'GA', 'Elbert', 'Elbert County, GA', 'coming_soon', 0),
('ga-emanuel', 'GA', 'Emanuel', 'Emanuel County, GA', 'coming_soon', 0),
('ga-evans', 'GA', 'Evans', 'Evans County, GA', 'coming_soon', 0),
('ga-fannin', 'GA', 'Fannin', 'Fannin County, GA', 'coming_soon', 0),
('ga-fayette', 'GA', 'Fayette', 'Fayette County, GA', 'coming_soon', 0),
('ga-floyd', 'GA', 'Floyd', 'Floyd County, GA', 'coming_soon', 0),
('ga-forsyth', 'GA', 'Forsyth', 'Forsyth County, GA', 'coming_soon', 0),
('ga-franklin', 'GA', 'Franklin', 'Franklin County, GA', 'coming_soon', 0),
('ga-fulton', 'GA', 'Fulton', 'Fulton County, GA', 'coming_soon', 0),
('ga-gilmer', 'GA', 'Gilmer', 'Gilmer County, GA', 'coming_soon', 0),
('ga-glascock', 'GA', 'Glascock', 'Glascock County, GA', 'coming_soon', 0),
('ga-glynn', 'GA', 'Glynn', 'Glynn County, GA', 'coming_soon', 0),
('ga-gordon', 'GA', 'Gordon', 'Gordon County, GA', 'coming_soon', 0),
('ga-grady', 'GA', 'Grady', 'Grady County, GA', 'coming_soon', 0),
('ga-greene', 'GA', 'Greene', 'Greene County, GA', 'coming_soon', 0),
('ga-gwinnett', 'GA', 'Gwinnett', 'Gwinnett County, GA', 'coming_soon', 0),
('ga-habersham', 'GA', 'Habersham', 'Habersham County, GA', 'coming_soon', 0),
('ga-hall', 'GA', 'Hall', 'Hall County, GA', 'coming_soon', 0),
('ga-hancock', 'GA', 'Hancock', 'Hancock County, GA', 'coming_soon', 0),
('ga-haralson', 'GA', 'Haralson', 'Haralson County, GA', 'coming_soon', 0),
('ga-harris', 'GA', 'Harris', 'Harris County, GA', 'coming_soon', 0),
('ga-hart', 'GA', 'Hart', 'Hart County, GA', 'coming_soon', 0),
('ga-heard', 'GA', 'Heard', 'Heard County, GA', 'coming_soon', 0),
('ga-henry', 'GA', 'Henry', 'Henry County, GA', 'coming_soon', 0),
('ga-houston', 'GA', 'Houston', 'Houston County, GA', 'coming_soon', 0),
('ga-irwin', 'GA', 'Irwin', 'Irwin County, GA', 'coming_soon', 0),
('ga-jackson', 'GA', 'Jackson', 'Jackson County, GA', 'coming_soon', 0),
('ga-jasper', 'GA', 'Jasper', 'Jasper County, GA', 'coming_soon', 0),
('ga-jeff-davis', 'GA', 'Jeff Davis', 'Jeff Davis County, GA', 'coming_soon', 0),
('ga-jefferson', 'GA', 'Jefferson', 'Jefferson County, GA', 'coming_soon', 0),
('ga-jenkins', 'GA', 'Jenkins', 'Jenkins County, GA', 'coming_soon', 0),
('ga-johnson', 'GA', 'Johnson', 'Johnson County, GA', 'coming_soon', 0),
('ga-jones', 'GA', 'Jones', 'Jones County, GA', 'coming_soon', 0),
('ga-lamar', 'GA', 'Lamar', 'Lamar County, GA', 'coming_soon', 0),
('ga-lanier', 'GA', 'Lanier', 'Lanier County, GA', 'coming_soon', 0),
('ga-laurens', 'GA', 'Laurens', 'Laurens County, GA', 'coming_soon', 0),
('ga-lee', 'GA', 'Lee', 'Lee County, GA', 'coming_soon', 0),
('ga-liberty', 'GA', 'Liberty', 'Liberty County, GA', 'coming_soon', 0),
('ga-lincoln', 'GA', 'Lincoln', 'Lincoln County, GA', 'coming_soon', 0),
('ga-long', 'GA', 'Long', 'Long County, GA', 'coming_soon', 0),
('ga-lowndes', 'GA', 'Lowndes', 'Lowndes County, GA', 'coming_soon', 0),
('ga-lumpkin', 'GA', 'Lumpkin', 'Lumpkin County, GA', 'coming_soon', 0),
('ga-macon', 'GA', 'Macon', 'Macon County, GA', 'coming_soon', 0),
('ga-madison', 'GA', 'Madison', 'Madison County, GA', 'coming_soon', 0),
('ga-marion', 'GA', 'Marion', 'Marion County, GA', 'coming_soon', 0),
('ga-mcduffie', 'GA', 'McDuffie', 'McDuffie County, GA', 'coming_soon', 0),
('ga-mcintosh', 'GA', 'McIntosh', 'McIntosh County, GA', 'coming_soon', 0),
('ga-meriwether', 'GA', 'Meriwether', 'Meriwether County, GA', 'coming_soon', 0),
('ga-miller', 'GA', 'Miller', 'Miller County, GA', 'coming_soon', 0),
('ga-mitchell', 'GA', 'Mitchell', 'Mitchell County, GA', 'coming_soon', 0),
('ga-monroe', 'GA', 'Monroe', 'Monroe County, GA', 'coming_soon', 0),
('ga-montgomery', 'GA', 'Montgomery', 'Montgomery County, GA', 'coming_soon', 0),
('ga-morgan', 'GA', 'Morgan', 'Morgan County, GA', 'coming_soon', 0),
('ga-murray', 'GA', 'Murray', 'Murray County, GA', 'coming_soon', 0),
('ga-muscogee', 'GA', 'Muscogee', 'Muscogee County, GA', 'coming_soon', 0),
('ga-newton', 'GA', 'Newton', 'Newton County, GA', 'coming_soon', 0),
('ga-oconee', 'GA', 'Oconee', 'Oconee County, GA', 'coming_soon', 0),
('ga-oglethorpe', 'GA', 'Oglethorpe', 'Oglethorpe County, GA', 'coming_soon', 0),
('ga-paulding', 'GA', 'Paulding', 'Paulding County, GA', 'coming_soon', 0),
('ga-peach', 'GA', 'Peach', 'Peach County, GA', 'coming_soon', 0),
('ga-pickens', 'GA', 'Pickens', 'Pickens County, GA', 'coming_soon', 0),
('ga-pierce', 'GA', 'Pierce', 'Pierce County, GA', 'coming_soon', 0),
('ga-pike', 'GA', 'Pike', 'Pike County, GA', 'coming_soon', 0),
('ga-polk', 'GA', 'Polk', 'Polk County, GA', 'coming_soon', 0),
('ga-pulaski', 'GA', 'Pulaski', 'Pulaski County, GA', 'coming_soon', 0),
('ga-putnam', 'GA', 'Putnam', 'Putnam County, GA', 'coming_soon', 0),
('ga-quitman', 'GA', 'Quitman', 'Quitman County, GA', 'coming_soon', 0),
('ga-rabun', 'GA', 'Rabun', 'Rabun County, GA', 'coming_soon', 0),
('ga-randolph', 'GA', 'Randolph', 'Randolph County, GA', 'coming_soon', 0),
('ga-richmond', 'GA', 'Richmond', 'Richmond County, GA', 'coming_soon', 0),
('ga-rockdale', 'GA', 'Rockdale', 'Rockdale County, GA', 'coming_soon', 0),
('ga-schley', 'GA', 'Schley', 'Schley County, GA', 'coming_soon', 0),
('ga-screven', 'GA', 'Screven', 'Screven County, GA', 'coming_soon', 0),
('ga-seminole', 'GA', 'Seminole', 'Seminole County, GA', 'coming_soon', 0),
('ga-spalding', 'GA', 'Spalding', 'Spalding County, GA', 'coming_soon', 0),
('ga-stephens', 'GA', 'Stephens', 'Stephens County, GA', 'coming_soon', 0),
('ga-stewart', 'GA', 'Stewart', 'Stewart County, GA', 'coming_soon', 0),
('ga-sumter', 'GA', 'Sumter', 'Sumter County, GA', 'coming_soon', 0),
('ga-talbot', 'GA', 'Talbot', 'Talbot County, GA', 'coming_soon', 0),
('ga-taliaferro', 'GA', 'Taliaferro', 'Taliaferro County, GA', 'coming_soon', 0),
('ga-tattnall', 'GA', 'Tattnall', 'Tattnall County, GA', 'coming_soon', 0),
('ga-taylor', 'GA', 'Taylor', 'Taylor County, GA', 'coming_soon', 0),
('ga-telfair', 'GA', 'Telfair', 'Telfair County, GA', 'coming_soon', 0),
('ga-terrell', 'GA', 'Terrell', 'Terrell County, GA', 'coming_soon', 0),
('ga-thomas', 'GA', 'Thomas', 'Thomas County, GA', 'coming_soon', 0),
('ga-tift', 'GA', 'Tift', 'Tift County, GA', 'coming_soon', 0),
('ga-toombs', 'GA', 'Toombs', 'Toombs County, GA', 'coming_soon', 0),
('ga-towns', 'GA', 'Towns', 'Towns County, GA', 'coming_soon', 0),
('ga-treutlen', 'GA', 'Treutlen', 'Treutlen County, GA', 'coming_soon', 0),
('ga-troup', 'GA', 'Troup', 'Troup County, GA', 'coming_soon', 0),
('ga-turner', 'GA', 'Turner', 'Turner County, GA', 'coming_soon', 0),
('ga-twiggs', 'GA', 'Twiggs', 'Twiggs County, GA', 'coming_soon', 0),
('ga-union', 'GA', 'Union', 'Union County, GA', 'coming_soon', 0),
('ga-upson', 'GA', 'Upson', 'Upson County, GA', 'coming_soon', 0),
('ga-walker', 'GA', 'Walker', 'Walker County, GA', 'coming_soon', 0),
('ga-walton', 'GA', 'Walton', 'Walton County, GA', 'coming_soon', 0),
('ga-ware', 'GA', 'Ware', 'Ware County, GA', 'coming_soon', 0),
('ga-warren', 'GA', 'Warren', 'Warren County, GA', 'coming_soon', 0),
('ga-washington', 'GA', 'Washington', 'Washington County, GA', 'coming_soon', 0),
('ga-wayne', 'GA', 'Wayne', 'Wayne County, GA', 'coming_soon', 0),
('ga-webster', 'GA', 'Webster', 'Webster County, GA', 'coming_soon', 0),
('ga-wheeler', 'GA', 'Wheeler', 'Wheeler County, GA', 'coming_soon', 0),
('ga-white', 'GA', 'White', 'White County, GA', 'coming_soon', 0),
('ga-whitfield', 'GA', 'Whitfield', 'Whitfield County, GA', 'coming_soon', 0),
('ga-wilcox', 'GA', 'Wilcox', 'Wilcox County, GA', 'coming_soon', 0),
('ga-wilkes', 'GA', 'Wilkes', 'Wilkes County, GA', 'coming_soon', 0),
('ga-wilkinson', 'GA', 'Wilkinson', 'Wilkinson County, GA', 'coming_soon', 0),
('ga-worth', 'GA', 'Worth', 'Worth County, GA', 'coming_soon', 0),

-- Hawaii (5 counties)
('hi-hawaii', 'HI', 'Hawaii', 'Hawaii County, HI', 'coming_soon', 0),
('hi-honolulu', 'HI', 'Honolulu', 'Honolulu County, HI', 'coming_soon', 0),
('hi-kalawao', 'HI', 'Kalawao', 'Kalawao County, HI', 'coming_soon', 0),
('hi-kauai', 'HI', 'Kauai', 'Kauai County, HI', 'coming_soon', 0),
('hi-maui', 'HI', 'Maui', 'Maui County, HI', 'coming_soon', 0),

-- Idaho (44 counties)
('id-ada', 'ID', 'Ada', 'Ada County, ID', 'coming_soon', 0),
('id-adams', 'ID', 'Adams', 'Adams County, ID', 'coming_soon', 0),
('id-bannock', 'ID', 'Bannock', 'Bannock County, ID', 'coming_soon', 0),
('id-bear-lake', 'ID', 'Bear Lake', 'Bear Lake County, ID', 'coming_soon', 0),
('id-benewah', 'ID', 'Benewah', 'Benewah County, ID', 'coming_soon', 0),
('id-bingham', 'ID', 'Bingham', 'Bingham County, ID', 'coming_soon', 0),
('id-blaine', 'ID', 'Blaine', 'Blaine County, ID', 'coming_soon', 0),
('id-boise', 'ID', 'Boise', 'Boise County, ID', 'coming_soon', 0),
('id-bonner', 'ID', 'Bonner', 'Bonner County, ID', 'coming_soon', 0),
('id-bonneville', 'ID', 'Bonneville', 'Bonneville County, ID', 'coming_soon', 0),
('id-boundary', 'ID', 'Boundary', 'Boundary County, ID', 'coming_soon', 0),
('id-butte', 'ID', 'Butte', 'Butte County, ID', 'coming_soon', 0),
('id-camas', 'ID', 'Camas', 'Camas County, ID', 'coming_soon', 0),
('id-canyon', 'ID', 'Canyon', 'Canyon County, ID', 'coming_soon', 0),
('id-caribou', 'ID', 'Caribou', 'Caribou County, ID', 'coming_soon', 0),
('id-cassia', 'ID', 'Cassia', 'Cassia County, ID', 'coming_soon', 0),
('id-clark', 'ID', 'Clark', 'Clark County, ID', 'coming_soon', 0),
('id-clearwater', 'ID', 'Clearwater', 'Clearwater County, ID', 'coming_soon', 0),
('id-custer', 'ID', 'Custer', 'Custer County, ID', 'coming_soon', 0),
('id-elmore', 'ID', 'Elmore', 'Elmore County, ID', 'coming_soon', 0),
('id-franklin', 'ID', 'Franklin', 'Franklin County, ID', 'coming_soon', 0),
('id-fremont', 'ID', 'Fremont', 'Fremont County, ID', 'coming_soon', 0),
('id-gem', 'ID', 'Gem', 'Gem County, ID', 'coming_soon', 0),
('id-gooding', 'ID', 'Gooding', 'Gooding County, ID', 'coming_soon', 0),
('id-idaho', 'ID', 'Idaho', 'Idaho County, ID', 'coming_soon', 0),
('id-jefferson', 'ID', 'Jefferson', 'Jefferson County, ID', 'coming_soon', 0),
('id-jerome', 'ID', 'Jerome', 'Jerome County, ID', 'coming_soon', 0),
('id-kootenai', 'ID', 'Kootenai', 'Kootenai County, ID', 'coming_soon', 0),
('id-latah', 'ID', 'Latah', 'Latah County, ID', 'coming_soon', 0),
('id-lemhi', 'ID', 'Lemhi', 'Lemhi County, ID', 'coming_soon', 0),
('id-lewis', 'ID', 'Lewis', 'Lewis County, ID', 'coming_soon', 0),
('id-lincoln', 'ID', 'Lincoln', 'Lincoln County, ID', 'coming_soon', 0),
('id-madison', 'ID', 'Madison', 'Madison County, ID', 'coming_soon', 0),
('id-minidoka', 'ID', 'Minidoka', 'Minidoka County, ID', 'coming_soon', 0),
('id-nez-perce', 'ID', 'Nez Perce', 'Nez Perce County, ID', 'coming_soon', 0),
('id-oneida', 'ID', 'Oneida', 'Oneida County, ID', 'coming_soon', 0),
('id-owyhee', 'ID', 'Owyhee', 'Owyhee County, ID', 'coming_soon', 0),
('id-payette', 'ID', 'Payette', 'Payette County, ID', 'coming_soon', 0),
('id-power', 'ID', 'Power', 'Power County, ID', 'coming_soon', 0),
('id-shoshone', 'ID', 'Shoshone', 'Shoshone County, ID', 'coming_soon', 0),
('id-teton', 'ID', 'Teton', 'Teton County, ID', 'coming_soon', 0),
('id-twin-falls', 'ID', 'Twin Falls', 'Twin Falls County, ID', 'coming_soon', 0),
('id-valley', 'ID', 'Valley', 'Valley County, ID', 'coming_soon', 0),
('id-washington', 'ID', 'Washington', 'Washington County, ID', 'coming_soon', 0)

ON CONFLICT (jurisdiction_code) DO NOTHING;
